/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         userIdentifier: "userIdentifier",
 *         engagement: "engagement"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         engagement: "engagement"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         engagement: "engagement"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         engagement: "engagement"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         engagement: "engagement"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         engagement: "engagement"
 *     }
 */
export interface EngageRequest {
    userIdentifier: string;
    groupIdentifier?: string;
    engagement: string;
}
