/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DoptApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CompleteRequest: core.serialization.Schema<
    serializers.CompleteRequest.Raw,
    Omit<DoptApi.CompleteRequest, "userIdentifier" | "groupIdentifier">
> = core.serialization.object({
    effect: core.serialization.string(),
});

export declare namespace CompleteRequest {
    interface Raw {
        effect: string;
    }
}
