/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DoptApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const EngageRequest: core.serialization.Schema<
    serializers.EngageRequest.Raw,
    Omit<DoptApi.EngageRequest, "userIdentifier" | "groupIdentifier">
> = core.serialization.object({
    engagement: core.serialization.string(),
});

export declare namespace EngageRequest {
    interface Raw {
        engagement: string;
    }
}
