/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../index";

export type GetResponseMessagesItemFieldsValue =
    | DoptApi.GetResponseMessagesItemFieldsValue.String
    | DoptApi.GetResponseMessagesItemFieldsValue.Number
    | DoptApi.GetResponseMessagesItemFieldsValue.Boolean
    | DoptApi.GetResponseMessagesItemFieldsValue.RichText;

export declare namespace GetResponseMessagesItemFieldsValue {
    interface String extends DoptApi.GetResponseMessagesItemFieldsValueString {
        type: "string";
    }

    interface Number extends DoptApi.GetResponseMessagesItemFieldsValueNumber {
        type: "number";
    }

    interface Boolean extends DoptApi.GetResponseMessagesItemFieldsValueBoolean {
        type: "boolean";
    }

    interface RichText extends DoptApi.GetResponseMessagesItemFieldsValueRichText {
        type: "richText";
    }
}
