/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetResponseMessagesItemStatus =
    | "Aborted"
    | "Completed"
    | "Created"
    | "Engaged"
    | "Qualified"
    | "Queued"
    | "Seen"
    | "Sent";

export const GetResponseMessagesItemStatus = {
    Aborted: "Aborted",
    Completed: "Completed",
    Created: "Created",
    Engaged: "Engaged",
    Qualified: "Qualified",
    Queued: "Queued",
    Seen: "Seen",
    Sent: "Sent",
} as const;
