/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../index";

export interface GetResponse {
    sid: string;
    uid: string;
    messages: DoptApi.GetResponseMessagesItem[];
}
