/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../index";

export interface GetResponseMessagesItem {
    uid: string;
    name: string;
    status: DoptApi.GetResponseMessagesItemStatus;
    channel: string;
    fields: Record<string, DoptApi.GetResponseMessagesItemFieldsValue>;
}
