/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetResponseMessagesItemFieldsValueRichText: core.serialization.ObjectSchema<
    serializers.GetResponseMessagesItemFieldsValueRichText.Raw,
    DoptApi.GetResponseMessagesItemFieldsValueRichText
> = core.serialization.object({
    sid: core.serialization.string(),
    value: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
});

export declare namespace GetResponseMessagesItemFieldsValueRichText {
    interface Raw {
        sid: string;
        value?: Record<string, unknown>[] | null;
    }
}
