/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetResponseMessagesItemFieldsValueString } from "./GetResponseMessagesItemFieldsValueString";
import { GetResponseMessagesItemFieldsValueNumber } from "./GetResponseMessagesItemFieldsValueNumber";
import { GetResponseMessagesItemFieldsValueBoolean } from "./GetResponseMessagesItemFieldsValueBoolean";
import { GetResponseMessagesItemFieldsValueRichText } from "./GetResponseMessagesItemFieldsValueRichText";

export const GetResponseMessagesItemFieldsValue: core.serialization.Schema<
    serializers.GetResponseMessagesItemFieldsValue.Raw,
    DoptApi.GetResponseMessagesItemFieldsValue
> = core.serialization
    .union("type", {
        string: GetResponseMessagesItemFieldsValueString,
        number: GetResponseMessagesItemFieldsValueNumber,
        boolean: GetResponseMessagesItemFieldsValueBoolean,
        richText: GetResponseMessagesItemFieldsValueRichText,
    })
    .transform<DoptApi.GetResponseMessagesItemFieldsValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetResponseMessagesItemFieldsValue {
    type Raw =
        | GetResponseMessagesItemFieldsValue.String
        | GetResponseMessagesItemFieldsValue.Number
        | GetResponseMessagesItemFieldsValue.Boolean
        | GetResponseMessagesItemFieldsValue.RichText;

    interface String extends GetResponseMessagesItemFieldsValueString.Raw {
        type: "string";
    }

    interface Number extends GetResponseMessagesItemFieldsValueNumber.Raw {
        type: "number";
    }

    interface Boolean extends GetResponseMessagesItemFieldsValueBoolean.Raw {
        type: "boolean";
    }

    interface RichText extends GetResponseMessagesItemFieldsValueRichText.Raw {
        type: "richText";
    }
}
