/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetResponseMessagesItemStatus } from "./GetResponseMessagesItemStatus";
import { GetResponseMessagesItemFieldsValue } from "./GetResponseMessagesItemFieldsValue";

export const GetResponseMessagesItem: core.serialization.ObjectSchema<
    serializers.GetResponseMessagesItem.Raw,
    DoptApi.GetResponseMessagesItem
> = core.serialization.object({
    uid: core.serialization.string(),
    name: core.serialization.string(),
    status: GetResponseMessagesItemStatus,
    channel: core.serialization.string(),
    fields: core.serialization.record(core.serialization.string(), GetResponseMessagesItemFieldsValue),
});

export declare namespace GetResponseMessagesItem {
    interface Raw {
        uid: string;
        name: string;
        status: GetResponseMessagesItemStatus.Raw;
        channel: string;
        fields: Record<string, GetResponseMessagesItemFieldsValue.Raw>;
    }
}
