/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetResponseMessagesItemFieldsValueString: core.serialization.ObjectSchema<
    serializers.GetResponseMessagesItemFieldsValueString.Raw,
    DoptApi.GetResponseMessagesItemFieldsValueString
> = core.serialization.object({
    sid: core.serialization.string(),
    value: core.serialization.string().optional(),
});

export declare namespace GetResponseMessagesItemFieldsValueString {
    interface Raw {
        sid: string;
        value?: string | null;
    }
}
