/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetResponseMessagesItem } from "./GetResponseMessagesItem";

export const GetResponse: core.serialization.ObjectSchema<serializers.GetResponse.Raw, DoptApi.GetResponse> =
    core.serialization.object({
        sid: core.serialization.string(),
        uid: core.serialization.string(),
        messages: core.serialization.list(GetResponseMessagesItem),
    });

export declare namespace GetResponse {
    interface Raw {
        sid: string;
        uid: string;
        messages: GetResponseMessagesItem.Raw[];
    }
}
