/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Channels } from "./api/resources/channels/client/Client";
import { Messages } from "./api/resources/messages/client/Client";

export declare namespace DoptApiClient {
    interface Options {
        environment?: core.Supplier<environments.DoptApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class DoptApiClient {
    constructor(protected readonly _options: DoptApiClient.Options) {}

    protected _channels: Channels | undefined;

    public get channels(): Channels {
        return (this._channels ??= new Channels(this._options));
    }

    protected _messages: Messages | undefined;

    public get messages(): Messages {
        return (this._messages ??= new Messages(this._options));
    }
}
